spring.application.name=MySawit

spring.datasource.url=${SPRING_DATASOURCE_URL:}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=${JWT_SECRET:012345678901234567890123456789012345}
jwt.expirationMs=${JWT_EXPIRATION_MS:86400000}

management.endpoints.web.exposure.include=${MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE:health,info,metrics,prometheus}
management.endpoint.health.show-details=${MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS:always}
management.prometheus.metrics.export.enabled=${MANAGEMENT_PROMETHEUS_METRICS_EXPORT_ENABLED:true}
management.metrics.tags.application=${spring.application.name}

monitoring.token=${MONITORING_TOKEN:}

midtrans.server.key=${MIDTRANS_SERVER_KEY:}
midtrans.client.key=${MIDTRANS_CLIENT_KEY:}
midtrans.is.production=${MIDTRANS_IS_PRODUCTION:false}
