package id.ac.ui.cs.advprog.mysawit.auth.serviceimpl;

import id.ac.ui.cs.advprog.mysawit.auth.dto.AuthRequest;
import id.ac.ui.cs.advprog.mysawit.auth.dto.AuthResponse;
import id.ac.ui.cs.advprog.mysawit.auth.dto.RegisterRequest;
import id.ac.ui.cs.advprog.mysawit.auth.model.Role;
import id.ac.ui.cs.advprog.mysawit.auth.model.User;
import id.ac.ui.cs.advprog.mysawit.auth.repository.UserRepository;
import id.ac.ui.cs.advprog.mysawit.auth.security.JwtUtil;
import id.ac.ui.cs.advprog.mysawit.auth.service.AuthService;

import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Service;

import java.util.Optional;

@Service
public class AuthServiceImpl implements AuthService {

    private final UserRepository userRepository;
    private final PasswordEncoder passwordEncoder;
    private final JwtUtil jwtUtil;

    public AuthServiceImpl(UserRepository userRepository, PasswordEncoder passwordEncoder, JwtUtil jwtUtil) {
        this.userRepository = userRepository;
        this.passwordEncoder = passwordEncoder;
        this.jwtUtil = jwtUtil;
    }

    @Override
    public AuthResponse login(AuthRequest request) {
        Optional<User> u = userRepository.findByUsername(request.getUsername());
        if (u.isEmpty()) {
            throw new RuntimeException("Invalid credentials");
        }
        User user = u.get();
        if (!passwordEncoder.matches(request.getPassword(), user.getPassword())) {
            throw new RuntimeException("Invalid credentials");
        }
        String token = jwtUtil.generateToken(user);
        return new AuthResponse(token);
    }

    @Override
    public void register(RegisterRequest request) {
        if (userRepository.existsByUsername(request.getUsername())) {
            throw new RuntimeException("Username already exists");
        }

        Role finalRole = request.getRole();
        finalRole = (finalRole == Role.ADMIN) ? Role.BURUH : finalRole;

        if (finalRole == Role.MANDOR
                && (request.getCertificationNumber() == null || request.getCertificationNumber().isBlank())) {
            throw new RuntimeException("Mandor must provide certificationNumber");
        }

        String cert = (finalRole == Role.MANDOR) ? request.getCertificationNumber() : null;

        // id = null
        // is fine, it will be generated by db
        User user = new User(
                null,
                request.getFullname(),
                request.getUsername(),
                passwordEncoder.encode(request.getPassword()),
                finalRole,
                cert,
                null
        );

        User savedUser = userRepository.save(user);
        return new RegisterResponse(
                savedUser.getId(),
                savedUser.getUsername(),
                savedUser.getFullname(),
                savedUser.getRole()
        );
    }
}
