package id.ac.ui.cs.advprog.mysawit.auth.model;

import jakarta.persistence.*;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

// DONT add fields
// Handling of relationships between users should be done using join tables, not here

@Data
@Entity
@Table(name = "users")
@NoArgsConstructor
@AllArgsConstructor
public class User {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(nullable = false)
    @NotBlank
    private String fullname;

    @Column(unique = true, nullable = false)
    @NotBlank
    private String username;

    @Column(nullable = false)
    @NotBlank
    private String password;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    @NotNull
    private Role role;

    // if role != MANDOR:
    //   certificationNumber = null
    private String certificationNumber; 

    // if role != BURUH:
    // mandorUsername = null
    private String mandorUsername;

    // support old tests that dont have id
    public User(String fullname, String username, String password, Role role, String certificationNumber,
            String mandorUsername) {
        // delegate to the all-args constructor generated by Lombok, with a null id
        this(null, fullname, username, password, role, certificationNumber, mandorUsername);
    }

    // support old tests that dont have mandorUsername
    public User(String fullname, String username, String password, Role role, String certificationNumber) {
        this(null, fullname, username, password, role, certificationNumber, null);
    }
}