global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'MySawit Backend Main'
    scheme: https
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['mysawit-backend-c16e06b7a623.herokuapp.com']
        labels:
          application: 'MySawit Backend'
          environment: 'main'

  - job_name: 'MySawit Backend Staging'
    scheme: https
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['mysawit-backend-staging-dece8597d7aa.herokuapp.com']
        labels:
          application: 'MySawit Backend'
          environment: 'staging'
