CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fullname VARCHAR(255) NOT NULL,
    username VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(255) NOT NULL,
    certification_number VARCHAR(255),
    mandor_username VARCHAR(255),
    CONSTRAINT uk_users_username UNIQUE (username)
);

CREATE TABLE kebun_sawit (
    id VARCHAR(255) PRIMARY KEY,
    nama_kebun VARCHAR(255) NOT NULL,
    kode_unik VARCHAR(255) NOT NULL,
    luas_hektare DOUBLE PRECISION NOT NULL,
    kiri_atas_x DOUBLE PRECISION,
    kiri_atas_y DOUBLE PRECISION,
    kiri_bawah_x DOUBLE PRECISION,
    kiri_bawah_y DOUBLE PRECISION,
    kanan_atas_x DOUBLE PRECISION,
    kanan_atas_y DOUBLE PRECISION,
    kanan_bawah_x DOUBLE PRECISION,
    kanan_bawah_y DOUBLE PRECISION,
    CONSTRAINT uk_kebun_sawit_kode_unik UNIQUE (kode_unik)
);

CREATE TABLE kebun_mandor (
    id VARCHAR(255) PRIMARY KEY,
    kebun_id VARCHAR(255) NOT NULL,
    mandor_id BIGINT NOT NULL,
    CONSTRAINT uk_kebun_mandor_kebun_id UNIQUE (kebun_id),
    CONSTRAINT uk_kebun_mandor_mandor_id UNIQUE (mandor_id)
);

CREATE TABLE kebun_supir (
    id VARCHAR(255) PRIMARY KEY,
    kebun_id VARCHAR(255) NOT NULL,
    supir_id BIGINT NOT NULL,
    CONSTRAINT uk_kebun_supir_supir_id UNIQUE (supir_id)
);

CREATE TABLE hasil_reports (
    id VARCHAR(255) PRIMARY KEY,
    worker_id VARCHAR(255) NOT NULL,
    hasil_date DATE NOT NULL,
    weight_kg DOUBLE PRECISION NOT NULL,
    news VARCHAR(2000) NOT NULL,
    locked BOOLEAN NOT NULL,
    status VARCHAR(255) NOT NULL,
    rejection_reason VARCHAR(1000),
    visible_for_pengiriman BOOLEAN NOT NULL
);

CREATE TABLE hasil_report_photos (
    hasil_report_id VARCHAR(255) NOT NULL,
    photo_url VARCHAR(255) NOT NULL,
    CONSTRAINT fk_hasil_report_photos_report
        FOREIGN KEY (hasil_report_id)
        REFERENCES hasil_reports (id)
        ON DELETE CASCADE
);

CREATE TABLE payrolls (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    total_kg NUMERIC(38, 2) NOT NULL,
    total_wage NUMERIC(38, 2) NOT NULL,
    status VARCHAR(255) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL
);

CREATE TABLE wage_settings (
    id VARCHAR(255) PRIMARY KEY,
    upah_buruh_per_kg NUMERIC(38, 2),
    upah_supir_per_kg NUMERIC(38, 2),
    upah_mandor_per_kg NUMERIC(38, 2)
);
