CREATE TABLE IF NOT EXISTS pengiriman_assignments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mandor_email VARCHAR(255) NOT NULL,
    supir_email VARCHAR(255) NOT NULL,
    muatan_kg DOUBLE PRECISION NOT NULL,
    tujuan VARCHAR(255) NOT NULL,
    status VARCHAR(255) NOT NULL,
    approval VARCHAR(255),
    note TEXT,
    admin_final_approval VARCHAR(255),
    admin_final_note TEXT,
    kilogram_diakui DOUBLE PRECISION,
    admin_final_reviewed_at TIMESTAMP(6),
    created_at TIMESTAMP(6),
    CONSTRAINT pengiriman_assignments_admin_final_approval_check
        CHECK (
            admin_final_approval IS NULL
            OR admin_final_approval IN ('APPROVED', 'REJECTED', 'PARTIALLY_REJECTED')
        )
);